const languageService = {
  english: {
    login: "Login",
    createWorkout: "CREATE WORKOUT",
    findWorkout: "FIND A WORKOUT",
    pastWorkouts: "PAST WORKOUTS",
    futureWorkouts: "FUTURE WORKOUTS",
    friendsWorkouts: "FRIENDS WORKOUTS",
    workoutInvites: "WORKOUT INVITES",
    noDescriptionYet: "No description yet",
    weeklyStatisticsChart: "Last week exercise duration (minutes)",
    weekDays: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
  },
  hebrew: {
    login: "התחבר",
    createWorkout: "יצירת אימון חדש",
    findWorkout: "חיפוש אימונים",
    pastWorkouts: "אימונים קודמים",
    futureWorkouts: "אימונים עתידיים",
    friendsWorkouts: "אימונים של חברים",
    workoutInvites: "הזמנות לאימונים",
    noDescriptionYet: "אין תיאור עדיין",
    weeklyStatisticsChart: "זמן אימון בשבוע האחרון (דקות)",
    weekDays: ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת"],
  },
};
export default languageService;
