const languageService = {
  english: {
    login: "Login",
    createWorkout: "CREATE WORKOUT",
    findWorkout: "FIND A WORKOUT",
    pastWorkouts: "PAST WORKOUTS",
    futureWorkouts: "FUTURE WORKOUTS",
    friendsWorkouts: "FRIENDS WORKOUTS",
    workoutInvites: "WORKOUT INVITES",
    noDescriptionYet: "No description yet",
    weeklyStatisticsChart: "Last week exercise duration (minutes)",
    weekDays: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    workoutTypes: [
      "Everything",
      "Resistance Training",
      "Walking",
      "Running",
      "Biking",
    ],
    chats: "Chats",
    createWorkout: "Create workout",
    when: "When?",
    openForEveryone: "Open for both sexes",
    location: "Location",
    gettingCurrentLocation: "Getting your location...",
    setLocation: "Set location",
    clickToChangeLocation: "Click to change location",
    webMapsError: "Can't use maps on web, try from your smartphone :)",
    newWorkout: "New workout",
    details: "Details",
    optionalText: "Optional text",
    workoutTimePeiod: "Workout time period (minutes)",
  },
  hebrew: {
    login: "התחבר",
    createWorkout: "יצירת אימון חדש",
    findWorkout: "חיפוש אימונים",
    pastWorkouts: "אימונים קודמים",
    futureWorkouts: "אימונים עתידיים",
    friendsWorkouts: "אימונים של חברים",
    workoutInvites: "הזמנות לאימונים",
    noDescriptionYet: "אין תיאור עדיין",
    weeklyStatisticsChart: "זמן אימון בשבוע האחרון (דקות)",
    weekDays: ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת"],
    chats: "צ'אטים",
    createWorkout: "יצירת אימון",
    when: "מתי?",
    openForEveryone: "פתוח גם לגברים וגם לנשים",
    location: "מיקום",
    gettingCurrentLocation: "טוען מיקום נוכחי...",
    setLocation: "בחירת מיקום",
    clickToChangeLocation: "שינוי מיקום",
    webMapsError:
      "אין אפשרות לראות את המפה בגרסה האינטרנטית, הורד את האפליקציה לחווית משתמש טובה יותר :)",
    newWorkout: "אימון חדש",
    details: "פרטים",
    optionalText: "לא חובה",
    workoutTypes: ["הכל", "אימון כוח", "הליכה", "ריצה", "רכיבת אופניים"],
    workoutTimePeiod: "זמן אימון (דקות)",
  },
};
export default languageService;
