const languageService = {
  english: {
    login: "Login",
    createWorkoutHomeBtn: "CREATE WORKOUT",
    findWorkoutHomeBtn: "FIND A WORKOUT",
    pastWorkoutsHomeBtn: "PAST WORKOUTS",
    futureWorkoutsHomeBtn: "FUTURE WORKOUTS",
    friendsWorkoutsHomeBtn: "FRIENDS WORKOUTS",
    workoutInvitesHomeBtn: "WORKOUT INVITES",
    createWorkout: "Create workout",
    findWorkout: "Find a workout",
    pastWorkouts: "Past workouts",
    futureWorkouts: "Future workouts",
    friendsWorkouts: "Friends workouts",
    workoutInvites: "Workout invites",
    noDescriptionYet: "No description yet",
    weeklyStatisticsChart: "Last week exercise duration (minutes)",
    weekDays: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    workoutTypes: [
      "Everything",
      "Resistance Training",
      "Walking",
      "Running",
      "Biking",
    ],
    chats: "Chats",
    createWorkout: "Create workout",
    when: "When?",
    openForEveryone: "Open for both sexes",
    location: "Location",
    gettingCurrentLocation: "Getting your location...",
    setLocation: "Set location",
    clickToChangeLocation: "Click to change location",
    webMapsError: "Can't use maps on web, try from your smartphone :)",
    newWorkout: "New workout",
    details: "Details",
    optionalText: "Optional text",
    workoutTimePeiod: "Workout time period (minutes)",
    language: "Language",
    chooseLanguage: "Choose language",
    showOnlineStatus: "Show online status",
    publicAccount: "Public account",
    settings: "Settings",
    privacy: "Privacy",
    changePassword: "Change password",
    logOut: "Log out",
    reportABug: "Report a bug or just suggest new features!",
    noChangesWereMade: "No changes were made",
    applyChanges: "Apply changes",
    search: "Search",
    searchUser: "Search user",
  },
  hebrew: {
    login: "התחבר",
    createWorkoutHomeBtn: "יצירת אימון חדש",
    findWorkoutHomeBtn: "חיפוש אימונים",
    pastWorkoutsHomeBtn: "אימונים קודמים",
    futureWorkoutsHomeBtn: "אימונים עתידיים",
    friendsWorkoutsHomeBtn: "אימונים של חברים",
    workoutInvitesHomeBtn: "הזמנות לאימונים",
    createWorkout: "יצירת אימון חדש",
    findWorkout: "חיפוש אימונים",
    pastWorkouts: "אימונים קודמים",
    futureWorkouts: "אימונים עתידיים",
    friendsWorkouts: "אימונים של חברים",
    workoutInvites: "הזמנות לאימונים",
    noDescriptionYet: "אין תיאור עדיין",
    weeklyStatisticsChart: "זמן אימון בשבוע האחרון (דקות)",
    weekDays: ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת"],
    chats: "צ'אטים",
    createWorkout: "יצירת אימון",
    when: "מתי?",
    openForEveryone: "פתוח גם לגברים וגם לנשים",
    location: "מיקום",
    gettingCurrentLocation: "טוען מיקום נוכחי...",
    setLocation: "בחירת מיקום",
    clickToChangeLocation: "שינוי מיקום",
    webMapsError:
      "אין אפשרות לראות את המפה בגרסה האינטרנטית, הורד את האפליקציה לחווית משתמש טובה יותר :)",
    newWorkout: "אימון חדש",
    details: "פרטים",
    optionalText: "לא חובה",
    workoutTypes: ["הכל", "אימון כוח", "הליכה", "ריצה", "רכיבת אופניים"],
    workoutTimePeiod: "זמן אימון (דקות)",
    language: "שפה",
    chooseLanguage: "בחר שפה",
    showOnlineStatus: "הראה כשאני מחובר",
    publicAccount: "משתמש ציבורי",
    settings: "הגדרות",
    privacy: "פרטיות",
    changePassword: "שינוי סיסמה",
    logOut: "התנתקות",
    reportABug: "דווח על באג או הצע פיצ'ר חדש שתרצה לראות פה! :)",
    noChangesWereMade: "לא נצפו שינויים",
    applyChanges: "שמירת השינויים",
    search: "חיפוש",
    searchUser: "חיפוש משתמש",
  },
};
export default languageService;
